### ISSUE TITLE
你好，请问如何修改样式，才能使标题呈现为多级标题？

### ISSUE THREAD

**Issue by ShampooDeng** [TomBener/pandoc-templates#1]
问题如标题
我想修改ref.docx中的`标题 2`，使其变为多级标题

![ref.docx中的`标题 2`](https://user-images.githubusercontent.com/30762004/161977387-aa19fa7d-26bd-46eb-85b8-6cdb17f2f7ec.png)

修改成如下样式，就像`ref.docx`中的`标题4`一样

![期望的‘标题2’样式](https://user-images.githubusercontent.com/30762004/161979138-da2fd4dd-2803-46d8-92af-96f7f57aa36e.png)

但是我发现word中的`修改样式`面板中的`格式-编号`并不支持我添加有关多级标题的属性（可能是我没有找到XP）

请问如何修改样式，才能使标题的编号呈现为多级标题？

**Comment by TomBener** [comment]
Microsoft Word 中设置各级标题编号有两种方式：

1. 在 Word 模板中修改。如果觉得麻烦的话，请看方法二。

2. 在 Pandoc 命令中加上 `--number-sections` 或 `-N`。参考链接：https://pandoc.org/MANUAL.html#option--number-sections

**Comment by ShampooDeng** [comment]
感谢回复，方法二很有帮助

我想知道，究竟应该**如何修改word模板，才能设置各级标题编号**？

因为我在自己尝试修改word模板时，修改了`标题样式`的`编号`属性

![image](https://user-images.githubusercontent.com/30762004/161995949-8a340505-adbb-49bc-9180-541e6f50ab9d.png)

但是结果只有标题只有一级，而且我也并没有找到其他可以修改各级标题编号的地方

![image](https://user-images.githubusercontent.com/30762004/161996172-d86c94e4-f8f5-4c27-bf3c-5460a87e9160.png)

**Comment by TomBener** [comment]
我使用的是 Word for Mac，不太清楚 Windows 上具体如何操作。

你可以参考一下这篇文章：https://zhuanlan.zhihu.com/p/336845648

**Comment by ShampooDeng** [comment]
非常感谢，又学到了新操作😊
